### ISSUE TITLE
Denoiser doesn't use RT preset with OpenImageDenoise

### ISSUE THREAD

**Issue by LegendWasTaken** [chunky-dev/chunky-denoiser#22]
In `OidnBinaryDenoiser`, the command line arguments don't use the RT preset that OIDN supplies in the native API. The RT preset allows you to use a different denoising method that's better suited for ray / path tracing. 

Possible solutions: Create a small wrapper of OIDN for chunky, to allow for you to set the denoising filter.

**Comment by leMaik** [comment]
https://github.com/OpenImageDenoise/oidn/blob/master/apps/oidnDenoise.cpp#L81
