### ISSUE TITLE
update to latest snapshots

### ISSUE THREAD

**Issue by Minecon724** [chunky-dev/chunky-denoiser#23]

**Comment by leMaik** [comment]
Thank you, I'll do after 2.4.0 is released. :)

**Comment by Minecon724** [comment]
i think you said that it will be released today

**Comment by leMaik** [comment]
[v0.4.0](https://github.com/chunky-dev/chunky-denoiser/releases/tag/v0.4.0) is compatible with Chunky 2.4.0
