### ISSUE TITLE
`DenoisedPathTracer` missing from Advanced tab

### ISSUE THREAD

**Issue by Matojeje** [chunky-dev/chunky-denoiser#37]
The `ALBEDO` and `NORMAL` renderers show up alongside the default `PathTracingRenderer`, but `DenoisedPathTracer` (mentioned in the [readme](https://github.com/chunky-dev/chunky-denoiser/blob/8184086fc823d04125308866d8092e200f886a34/README.md#usage)) is nowhere to be seen.

![obrazek](https://user-images.githubusercontent.com/3956863/212751545-5ececc5c-5593-45e6-9eec-bbe27775e3d9.png)

However, denoising still works (probably) as intended, since the render process starts out by first rendering the normal and albedo passes before anything else, and the denoised image *can* be found in the scene's `snapshots` folder:

![obrazek](https://user-images.githubusercontent.com/3956863/212752863-7df81b63-85f6-4e16-a23d-fef3f87e9109.png)

- Chunky version: 2.4.4
- Denoiser Plugin version: 0.4.0
- OIDN package: oidn-1.4.3.x64.vc14.windows
- Java version: 17.0.1.12 (Adoptium JDK)
- JavaFX SDK version: 18.0.2
- OS: Windows 10 Home x64 v1909 (build 18363.1556)

**Comment by Peregrine05** [comment]
The README that you read is for a WIP newer version of the plugin that is not yet released. The `DenoisedPathTracer` is not in the 0.4.0 version of the plugin. [This README](https://github.com/chunky-dev/chunky-denoiser/blob/4d4db51a4a81f77c24cc1def717686c9df67a95d/README.md) is for the 0.4.0 version of the Denoiser plugin.

**Comment by Matojeje** [comment]
Got it, thanks!

**Comment by leMaik** [comment]
https://github.com/chunky-dev/chunky-denoiser/releases/tag/v0.5.0-pre1
