### ISSUE TITLE
DenoisedPathTracer does not appear as an option in the Renderer drop-down menu

### ISSUE THREAD

**Issue by Faandyy** [chunky-dev/chunky-denoiser#39]
As stated. It is just not there. I got two other options though - ALBEDO and NORMAL. I have no idea what to do with this.

**Comment by Peregrine05** [comment]
See #37 for an explanation.

**Comment by Faandyy** [comment]
> See #37 for an explanation.

Unline the member in question, I do not get denoised images in my snapshots folder.

**Comment by Peregrine05** [comment]
Have you downloaded OIDN and set it up according to the instructions?
https://chunky-dev.github.io/docs/plugins/plugin_list/#denoising-plugin

If so, have you rendered to the Target SPP?

**Comment by Faandyy** [comment]
> Have you downloaded OIDN and set it up according to the instructions? https://chunky-dev.github.io/docs/plugins/plugin_list/#denoising-plugin
> 
> If so, have you rendered to the Target SPP?

Sorry, my bad, I just looked some more and it is there. Just very confused about the whole thing.

**Comment by leMaik** [comment]
https://github.com/chunky-dev/chunky-denoiser/releases/tag/v0.5.0-pre1
